name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  unix-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - 27.2
          - 28.2
          - 29.4
    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.16.0

      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'

      - name: Install requirements
        run: |
          echo "$HOME/.cask/bin" >> $GITHUB_PATH
          echo "$HOME/bin" >> $GITHUB_PATH

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.80.1
          components: clippy, rustfmt

      - name: Run tests
        run: |
          just build
          just test
